"""initial schema

First tracked Alembic revision for copilot-platform. Establishes the full
current schema in one migration — the A4 conversation/message model plus the
sidebar-management columns added on top of it (copilot_conversation_groups,
Conversation.pinned/group_id/sort_order/forked_from_id) — rather than
retroactively versioning the pre-Alembic Base.metadata.create_all() state.
Autogenerated from app/models.py against an empty database.

Revision ID: e5dcac32db65
Revises:
Create Date: 2026-08-10 01:15:40.125964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5dcac32db65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('copilot_conversation_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('sort_order', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_conversation_groups_user_id'), 'copilot_conversation_groups', ['user_id'], unique=False)
    op.create_index(op.f('ix_copilot_conversation_groups_workspace_id'), 'copilot_conversation_groups', ['workspace_id'], unique=False)
    op.create_table('copilot_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('title_source', sa.Enum('SYSTEM', 'USER', name='titlesource'), nullable=False),
    sa.Column('agent_type', sa.Enum('DEFAULT', 'SQL_EXPERT', 'EXPERIMENTATION', 'DATA_EXPLORATION', 'MIGRATION', name='agenttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='conversationstatus'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Float(), nullable=False),
    sa.Column('forked_from_id', sa.String(length=36), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_id'], ['copilot_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['copilot_conversation_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index('ix_conv_user_workspace_status', 'copilot_conversations', ['user_id', 'workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_group_id'), 'copilot_conversations', ['group_id'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_last_message_at'), 'copilot_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_pinned'), 'copilot_conversations', ['pinned'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_status'), 'copilot_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_user_id'), 'copilot_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_copilot_conversations_workspace_id'), 'copilot_conversations', ['workspace_id'], unique=False)
    op.create_table('copilot_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='messagestatus'), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('suggested_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['copilot_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_conversation_id'), 'copilot_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_created_at'), 'copilot_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_copilot_messages_run_id'), 'copilot_messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_status'), 'copilot_messages', ['status'], unique=False)
    op.create_index('ix_msg_conv_created', 'copilot_messages', ['conversation_id', 'created_at'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_msg_conv_created', table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_status'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_run_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_created_at'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_conversation_id'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index(op.f('ix_copilot_conversations_workspace_id'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_user_id'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_status'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_pinned'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_last_message_at'), table_name='copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversations_group_id'), table_name='copilot_conversations')
    op.drop_index('ix_conv_user_workspace_status', table_name='copilot_conversations')
    op.drop_table('copilot_conversations')
    op.drop_index(op.f('ix_copilot_conversation_groups_workspace_id'), table_name='copilot_conversation_groups')
    op.drop_index(op.f('ix_copilot_conversation_groups_user_id'), table_name='copilot_conversation_groups')
    op.drop_table('copilot_conversation_groups')
